---
name: container with latest rustic built

env:
  IMAGE_NAME: quay.io/ibotty/rustic

on:
  workflow_dispatch:
  schedule:
  - cron: '42 * * * *' # hourly

jobs:
  latest_rustic:
    name: rustic version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_latest_rustic.outputs.version }}
    steps:
    - name: Get latest rustic release
      id: get_latest_rustic
      shell: bash
      run: |
        set -euo pipefail
        get_latest_github_release() {
          local url="https://api.github.com/repos/$1/releases/latest"
          curl -fsSLH 'Accept: application/json' "$url" | jq -cr .tag_name
        }
        rustic_version="$(get_latest_github_release rustic-rs/rustic)"
        echo "discovered  rustic-rs/rustic $rustic_version"

        echo "version=$rustic_version" >> $GITHUB_OUTPUT

  image_tags:
    name: Image tags
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.image_tags.outputs.tags }}
    steps:
    - name: get all image tags (excluding latest)
      id: image_tags
      shell: bash
      run: |
        set -euo pipefail
        get_image_tags() {
          skopeo inspect "docker://$1" | jq -cr '.RepoTags[]'
        }
        image_tags="$(get_image_tags "${{ env.IMAGE_NAME }}" | grep -Ev '^latest$' | xargs)"
        echo "discovered image tags for ${{ env.IMAGE_NAME }}: $image_tags"
        echo tags=\"$image_tags\" >> $GITHUB_OUTPUT

  build:
    name: Trigger build of new image
    needs: [latest_rustic, image_tags]
    if: ${{ ! contains(needs.image_tags.outputs.tags, needs.latest_rustic.outputs.version) }}
    uses: ./.github/workflows/container-build.yml
    with:
      tags: latest ${{ needs.latest_rustic.outputs.version }}
      rustic_version: ${{ needs.latest_rustic.outputs.version }}
    secrets: inherit
